### ISSUE TITLE
Use branch name when publish

### ISSUE THREAD

**Issue by arnaudroques** [plantuml/plantuml-wasm#29]
Would it be possible to use branch name when publishing the demo ?

This way https://plantuml.github.io/plantuml-wasm/ would become https://plantuml.github.io/plantuml-wasm/main/

The interest is that we will be able to work on a different branch when developping (let's say develop).

So we could test the result here https://plantuml.github.io/plantuml-wasm/develop/

Once it will work on the branch, we will merge it into main.

This way https://plantuml.github.io/plantuml-wasm/main/ will always be working.

Since we would like to make an official announcement, we must provide something always on for users.
I'm sure it will make some noise :-)

@sakirtemel Could we put your name in this future announcement, you definitively deserve a huge kudos !

**Comment by sakirtemel** [comment]
I actually thought about the same, what we need is some sort of a Review Apps / environments. I haven't done it in Github Pages before, but I worked a lot with that especially in Heroku. Technically, it's possible, I'll prioritize that, as I wanted to also work on faster page publishing. The ideal flow would be, whenever there's a new PR, it should generate a new link specific to that PR/branch.

> Since we would like to make an official announcement, we must provide something always on for users.
> I'm sure it will make some noise :-)

Super exciting! Are you considering to have a separate subdomain for that, or it should rather live under github.io ?

Also, for before launch, I sent an email to cheerpj to be clear about their [licenses](https://leaningtech.com/cheerpj-licensing/) (it's free to experiment or it's free for non-profit). I'll keep you posted.

> @sakirtemel Could we put your name in this future announcement, you definitively deserve a huge kudos !

😊 it was actually a pleasure to work together for me. I'd be happy to be listed as a contributor there :)

**Comment by arnaudroques** [comment]
> I actually thought about the same, what we need is some sort of a Review Apps / environments. I haven't done it in Github Pages before, but I worked a lot with that especially in Heroku. Technically, it's possible, I'll prioritize that, as I wanted to also work on faster page publishing. The ideal flow would be, whenever there's a new PR, it should generate a new link specific to that PR/branch.
> 

Great, take your time do find the best/easiest solution. Whether it's a PR or a branch is fine for us.
Just tell us when it will be ready.


> Super exciting! Are you considering to have a separate subdomain for that, or it should rather live under github.io ?
> 

No, we can stay live on github.io
The real end goal is that it will be integrated natively by GitHub for *all* projects hosted by them, so let's stick to github.io (even if they will probably duplicate this on their own internal infrastructure gin that case)
In the meantime, I'm sure a lot of developers will use this for their projects and create new plugins.



> Also, for before launch, I sent an email to cheerpj to be clear about their [licenses](https://leaningtech.com/cheerpj-licensing/) (it's free to experiment or it's free for non-profit). I'll keep you posted.
> 

Would you mind forward me a copy of that email (plantuml@gmail.com)? I also wrote to them :-)
I will copy you on my future emails if you wish.


> blush it was actually a pleasure to work together for me.

Pleasure 100% shared!
I can't believe it only took a few days to get a fully functional solution!

**Comment by arnaudroques** [comment]
> my current workaround solution would be having a separate repo for the non-production builds, what are your thoughts o all these options?

Make sense. Just created https://github.com/plantuml/plantuml-wasm-dev :-)
