### ISSUE TITLE
Preload the dependencies for faster startup

### ISSUE THREAD

**Issue by sakirtemel** [plantuml/plantuml-wasm#8]
Cheerpj suggests declaring preloaded assets can speed up the startup time significantly

https://docs.leaningtech.com/cheerpj/Startup-time-optimization

**Comment by sakirtemel** [comment]
first attempt https://github.com/plantuml/plantuml-wasm/commit/c6197b961eac45d928948e90902954b66d364807

**Comment by arnaudroques** [comment]
Supplicate of https://github.com/plantuml/plantuml-wasm/issues/5 ?
